/**
 * Comprehensive Cross-Compatible Emoji Library
 * Version 4.5 - Last Update on 11/01/2025 - Search Pro Configuration Loading - Google Sheets / CSV / Business JSON integration, runtime synchronization, Exact matches config, Silence Console Fix
 * Organized by standard Unicode categories with focus on universal compatibility
 * Complete implementation with 1751+ carefully selected emojis
 */

window.EmojiLibrary = {
  // Smileys & Emotion - Highly compatible across platforms
  smileysEmotion: {
    // Face-smiling
    faceSmiling: [
      "💋",
      "😀",
      "😃",
      "😄",
      "😁",
      "😆",
      "😅",
      "🤣",
      "😂",
      "🙂",
      "🙃",
      "😉",
      "😊",
      "😇",
    ],
    // Face-affection
    faceAffection: ["🥰", "😍", "🤩", "😘", "😗", "☺️", "😚", "😙", "🥲"],
    // Face-tongue
    faceTongue: ["😋", "😛", "😜", "🤪", "😝", "🤑"],
    // Face-hand
    faceHand: ["🤗", "🤭", "🤫", "🤔", "🤐", "🤨", "😐", "😑", "😶", "😏", "😒", "🙄", "😬", "🤥"],
    // Face-neutral-skeptical
    faceNeutralSkeptical: [
      "😌",
      "😔",
      "😪",
      "🤤",
      "😴",
      "😷",
      "🤒",
      "🤕",
      "🤢",
      "🤮",
      "🤧",
      "🥵",
      "🥶",
      "🥴",
      "😵",
      "🤯",
    ],
    // Face-negative
    faceNegative: [
      "😕",
      "😟",
      "🙁",
      "☹️",
      "😮",
      "😯",
      "😲",
      "😳",
      "🥺",
      "😦",
      "😧",
      "😨",
      "😰",
      "😥",
      "😢",
      "😭",
      "😱",
      "😖",
      "😣",
      "😞",
      "😓",
      "😩",
      "😫",
      "🥱",
    ],
    // Face-costume
    faceCostume: ["💀", "👻", "👽", "🤖", "😺", "😸", "😹", "😻", "😼", "😽", "🙀", "😿", "😾"],
    // Emotion
    emotion: [
      "💋",
      "💌",
      "💘",
      "💝",
      "💖",
      "💗",
      "💓",
      "💞",
      "💕",
      "💟",
      "❣️",
      "💔",
      "❤️",
      "🧡",
      "💛",
      "💚",
      "💙",
      "💜",
      "🤎",
      "🖤",
      "🤍",
      "💯",
      "💢",
      "💥",
      "💫",
      "💦",
      "💨",
      "🕳️",
      "💣",
      "💬",
      "👁️‍🗨️",
      "🗨️",
      "🗯️",
      "💭",
      "💤",
    ],
  },

  // People & Body - Common gestures and body parts
  peopleBody: {
    // Hand-fingers-open
    handFingersOpen: [
      "👋",
      "🤚",
      "🖐️",
      "✋",
      "🖖",
      "👌",
      "🤌",
      "🤏",
      "✌️",
      "🤞",
      "🤟",
      "🤘",
      "🤙",
      "👈",
      "👉",
      "👆",
      "🖕",
      "👇",
      "☝️",
      "👍",
      "👎",
      "✊",
      "👊",
      "🤛",
      "🤜",
      "👏",
      "🙌",
      "👐",
      "🤲",
      "🤝",
      "🙏",
    ],
    // Body-parts
    bodyParts: [
      "👪",
      "👨‍👩‍👧",
      "👨‍👩‍👧‍👦",
      "👨‍👩‍👦‍👦",
      "👨‍👩‍👧‍👧",
      "👨‍👨‍👦",
      "👨‍👨‍👧",
      "👨‍👨‍👧‍👦",
      "👨‍👨‍👦‍👦",
      "👨‍👨‍👧‍👧",
      "👩‍👩‍👦",
      "👩‍👩‍👧",
      "👩‍👩‍👧‍👦",
      "👩‍👩‍👦‍👦",
      "👩‍👩‍👧‍👧",
      "👨‍👦",
      "👨‍👦‍👦",
      "👨‍👧",
      "👨‍👧‍👦",
      "👨‍👧‍👧",
      "👩‍👦",
      "👩‍👦‍👦",
      "👩‍👧",
      "👩‍👧‍👦",
      "👩‍👧‍👧",
    ],
    // Person
    person: ["👶", "🧒", "👦", "👧", "🧑", "👱", "👨", "🧔", "👩", "🧓", "👴", "👵"],
    // Person-gesture
    personGesture: ["🙍", "🙎", "🙅", "🙆", "💁", "🙋", "🧏", "🙇", "🤦", "🤷"],
    // Person-role
    personRole: [
      "👮",
      "🕵️",
      "💂",
      "👷",
      "🤴",
      "👸",
      "👳",
      "👲",
      "🧕",
      "🤵",
      "👰",
      "🤰",
      "🤱",
      "👼",
      "🎅",
      "🤶",
      "🦸",
      "🦹",
      "🧙",
      "🧚",
      "🧛",
      "🧜",
      "🧝",
      "🧞",
      "🧟",
      "💆",
      "💇",
      "🚶",
      "🧍",
      "🧎",
      "🏃",
      "💃",
      "🕺",
      "🕴️",
      "👯",
      "🧖",
      "🧗",
      "🤺",
      "🏇",
      "⛷️",
      "🏂",
      "🏌️",
      "🏄",
      "🚣",
      "🏊",
      "⛹️",
      "🏋️",
      "🚴",
      "🚵",
      "🤸",
      "🤼",
      "🤽",
      "🤾",
      "🤹",
      "🧘",
    ],
  },

  // Animals & Nature - Universal favorites
  animalsNature: {
    // Animal-mammal
    animalMammal: [
      "🐵",
      "🐒",
      "🦍",
      "🦧",
      "🐶",
      "🐕",
      "🦮",
      "🐩",
      "🐺",
      "🦊",
      "🦝",
      "🐱",
      "🐈",
      "🦁",
      "🐯",
      "🐅",
      "🐆",
      "🐴",
      "🐎",
      "🦄",
      "🦓",
      "🦌",
      "🐮",
      "🐂",
      "🐃",
      "🐄",
      "🐷",
      "🐖",
      "🐗",
      "🐽",
      "🐏",
      "🐑",
      "🐐",
      "🐪",
      "🐫",
      "🦙",
      "🦒",
      "🐘",
      "🦏",
      "🦛",
      "🐭",
      "🐁",
      "🐀",
      "🐹",
      "🐰",
      "🐇",
      "🐿️",
      "🦔",
      "🦇",
      "🐻",
      "🐨",
      "🐼",
      "🦥",
      "🦦",
      "🦨",
      "🦘",
      "🦡",
    ],
    // Animal-bird
    animalBird: [
      "🦃",
      "🐔",
      "🐓",
      "🐣",
      "🐤",
      "🐥",
      "🐦",
      "🐧",
      "🕊️",
      "🦅",
      "🦆",
      "🦢",
      "🦉",
      "🦩",
      "🦚",
      "🦜",
    ],
    // Animal-amphibian
    animalAmphibian: ["🐸"],
    // Animal-reptile
    animalReptile: ["🐊", "🐢", "🦎", "🐍", "🐲", "🐉", "🦕", "🦖"],
    // Animal-marine
    animalMarine: [
      "🐳",
      "🐋",
      "🐬",
      "🐟",
      "🐠",
      "🐡",
      "🦈",
      "🐙",
      "🐚",
      "🐌",
      "🦋",
      "🐛",
      "🐜",
      "🐝",
      "🐞",
      "🦗",
      "🕷️",
      "🕸️",
      "🦂",
      "🦟",
      "🦠",
    ],
    // Plant-flower
    plantFlower: ["💐", "🌸", "💮", "🏵️", "🌹", "🥀", "🌺", "🌻", "🌼", "🌷"],
    // Plant-other
    plantOther: ["🌱", "🌲", "🌳", "🌴", "🌵", "🌾", "🌿", "☘️", "🍀", "🍁", "🍂", "🍃"],
  },

  // Food & Drink - Universally recognized
  foodDrink: {
    // Food-fruit
    foodFruit: [
      "🍇",
      "🍈",
      "🍉",
      "🍊",
      "🍋",
      "🍌",
      "🍍",
      "🥭",
      "🍎",
      "🍏",
      "🍐",
      "🍑",
      "🍒",
      "🍓",
      "🥝",
      "🍅",
      "🥥",
    ],
    // Food-vegetable
    foodVegetable: [
      "🥑",
      "🍆",
      "🥔",
      "🥕",
      "🌽",
      "🌶️",
      "🥒",
      "🥬",
      "🥦",
      "🧄",
      "🧅",
      "🍄",
      "🥜",
      "🌰",
    ],
    // Food-prepared
    foodPrepared: [
      "🍞",
      "🥐",
      "🥖",
      "🥨",
      "🥯",
      "🥞",
      "🧇",
      "🧀",
      "🍖",
      "🍗",
      "🥩",
      "🥓",
      "🍔",
      "🍟",
      "🍕",
      "🌭",
      "🥪",
      "🌮",
      "🌯",
      "🥙",
      "🧆",
      "🥚",
      "🍳",
      "🥘",
      "🍲",
      "🥣",
      "🥗",
      "🍿",
      "🧈",
      "🧂",
      "🥫",
    ],
    // Food-asian
    foodAsian: [
      "🍱",
      "🍘",
      "🍙",
      "🍚",
      "🍛",
      "🍜",
      "🍝",
      "🍠",
      "🍢",
      "🍣",
      "🍤",
      "🍥",
      "🥮",
      "🍡",
      "🥟",
      "🥠",
      "🥡",
    ],
    // Food-sweet
    foodSweet: ["🍦", "🍧", "🍨", "🍩", "🍪", "🎂", "🍰", "🧁", "🥧", "🍫", "🍬", "🍭", "🍮", "🍯"],
    // Drink
    drink: [
      "🍼",
      "🥛",
      "☕",
      "🍵",
      "🍶",
      "🍾",
      "🍷",
      "🍸",
      "🍹",
      "🍺",
      "🍻",
      "🥂",
      "🥃",
      "🥤",
      "🧃",
      "🧉",
      "🧊",
    ],
    // Dishware
    dishware: ["🥢", "🍽️", "🍴", "🥄", "🔪", "🏺"],
  },

  // Travel & Places - Locations and transportation
  travelPlaces: {
    // Place-map
    placeMap: ["🌍", "🌎", "🌏", "🌐", "🗺️", "🗾", "🧭"],
    // Place-geographic
    placeGeographic: [
      "🏔️",
      "⛰️",
      "🌋",
      "🗻",
      "🏕️",
      "🏖️",
      "🏜️",
      "🏝️",
      "🏞️",
      "🏟️",
      "🏛️",
      "🏗️",
      "🧱",
      "🏘️",
      "🏚️",
      "🏠",
      "🏡",
      "🏢",
      "🏣",
      "🏤",
      "🏥",
      "🏦",
      "🏨",
      "🏩",
      "🏪",
      "🏫",
      "🏬",
      "🏭",
      "🏯",
      "🏰",
      "💒",
      "🗼",
      "🗽",
      "⛪",
      "🕌",
      "🛕",
      "🕍",
      "⛩️",
      "🕋",
      "⛲",
      "⛺",
      "🏙️",
      "🌄",
      "🌅",
      "🌆",
      "🌇",
      "🌃",
      "🌉",
      "🌌",
      "🎠",
      "🎡",
      "🎢",
      "💈",
      "🎪",
    ],
    // Transport-ground
    transportGround: [
      "🚂",
      "🚃",
      "🚄",
      "🚅",
      "🚆",
      "🚇",
      "🚈",
      "🚉",
      "🚊",
      "🚝",
      "🚞",
      "🚋",
      "🚌",
      "🚍",
      "🚎",
      "🚐",
      "🚑",
      "🚒",
      "🚓",
      "🚔",
      "🚕",
      "🚖",
      "🚗",
      "🚘",
      "🚙",
      "🚚",
      "🚛",
      "🚜",
      "🏎️",
      "🏍️",
      "🛵",
      "🦽",
      "🦼",
      "🛺",
      "🚲",
      "🛴",
      "🛹",
      "🚏",
      "🛣️",
      "🛤️",
      "🛢️",
      "⛽",
      "🚨",
      "🚥",
      "🚦",
      "🛑",
      "🚧",
    ],
    // Transport-water
    transportWater: ["⚓", "⛵", "🛶", "🚤", "🛳️", "⛴️", "🛥️", "🚢"],
    // Transport-air
    transportAir: ["✈️", "🛩️", "🛫", "🛬", "🪂", "💺", "🚁", "🚟", "🚠", "🚡", "🛰️", "🚀", "🛸"],
    // Hotel
    hotel: ["🛎️", "🧳"],
    // Time
    time: [
      "⌛",
      "⏳",
      "⌚",
      "⏰",
      "⏱️",
      "⏲️",
      "🕰️",
      "🕛",
      "🕧",
      "🕐",
      "🕜",
      "🕑",
      "🕝",
      "🕒",
      "🕞",
      "🕓",
      "🕟",
      "🕔",
      "🕠",
      "🕕",
      "🕡",
      "🕖",
      "🕢",
      "🕗",
      "🕣",
      "🕘",
      "🕤",
      "🕙",
      "🕥",
      "🕚",
      "🕦",
    ],
    // Sky & weather
    skyWeather: [
      "🌑",
      "🌒",
      "🌓",
      "🌔",
      "🌕",
      "🌖",
      "🌗",
      "🌘",
      "🌙",
      "🌚",
      "🌛",
      "🌜",
      "🌡️",
      "☀️",
      "🌝",
      "🌞",
      "🪐",
      "⭐",
      "🌟",
      "🌠",
      "🌌",
      "☁️",
      "⛅",
      "⛈️",
      "🌤️",
      "🌥️",
      "🌦️",
      "🌧️",
      "🌨️",
      "🌩️",
      "🌪️",
      "🌫️",
      "🌬️",
      "🌀",
      "🌈",
      "🌂",
      "☂️",
      "☔",
      "⛱️",
      "⚡",
      "❄️",
      "☃️",
      "⛄",
      "☄️",
      "🔥",
      "💧",
      "🌊",
    ],
  },

  // Activities - Sports and events
  activities: {
    // Event
    event: [
      "🎃",
      "🎄",
      "🎆",
      "🎇",
      "🧨",
      "✨",
      "🎈",
      "🎉",
      "🎊",
      "🎋",
      "🎍",
      "🎎",
      "🎏",
      "🎐",
      "🎑",
      "🧧",
      "🎀",
      "🎁",
      "🎗️",
      "🎟️",
      "🎫",
    ],
    // Award-medal
    awardMedal: [
      "🏆",
      "🏅",
      "🥇",
      "🥈",
      "🥉",
      "⚽",
      "⚾",
      "🥎",
      "🏀",
      "🏐",
      "🏈",
      "🏉",
      "🎾",
      "🥏",
      "🎳",
      "🏏",
      "🏑",
      "🏒",
      "🥍",
      "🏓",
      "🏸",
      "🥊",
      "🥋",
      "🥅",
      "⛳",
      "⛸️",
      "🎣",
      "🤿",
      "🎽",
      "🎿",
      "🛷",
      "🥌",
    ],
    // Game
    game: [
      "🎯",
      "🪀",
      "🪁",
      "🎱",
      "🔮",
      "🧿",
      "🎮",
      "🕹️",
      "🎰",
      "🎲",
      "🧩",
      "🧸",
      "♠️",
      "♥️",
      "♦️",
      "♣️",
      "♟️",
      "🃏",
      "🀄",
      "🎴",
      "🎭",
      "🖼️",
      "🎨",
      "🧵",
      "🧶",
    ],
  },

  // Objects - Common items
  objects: {
    // Clothing
    clothing: [
      "👓",
      "🕶️",
      "🥽",
      "🥼",
      "🦺",
      "👔",
      "👕",
      "👖",
      "🧣",
      "🧤",
      "🧥",
      "🧦",
      "👗",
      "👘",
      "🥻",
      "🩱",
      "🩲",
      "🩳",
      "👙",
      "👚",
      "👛",
      "👜",
      "👝",
      "🛍️",
      "🎒",
      "👞",
      "👟",
      "🥾",
      "🥿",
      "👠",
      "👡",
      "🩰",
      "👢",
      "👑",
      "👒",
      "🎩",
      "🎓",
      "🧢",
      "⛑️",
      "📿",
      "💄",
      "💍",
      "💎",
    ],
    // Sound
    sound: [
      "🔇",
      "🔈",
      "🔉",
      "🔊",
      "📢",
      "📣",
      "📯",
      "🔔",
      "🔕",
      "🎼",
      "🎵",
      "🎶",
      "🎙️",
      "🎚️",
      "🎛️",
      "🎤",
      "🎧",
      "📻",
    ],
    // Music
    music: ["🎷", "🎸", "🎹", "🎺", "🎻", "🪕", "🥁"],
    // Musical-keyboard
    musicalKeyboard: ["📱", "📲", "☎️", "📞", "📟", "📠"],
    // Computer
    computer: ["🔋", "🔌", "💻", "🖥️", "🖨️", "⌨️", "🖱️", "🖲️", "💽", "💾", "💿", "📀", "🧮"],
    // Light & video
    lightVideo: [
      "🎥",
      "🎞️",
      "📽️",
      "🎬",
      "📺",
      "📷",
      "📸",
      "📹",
      "📼",
      "🔍",
      "🔎",
      "🕯️",
      "💡",
      "🔦",
      "🏮",
      "🪔",
    ],
    // Book-paper
    bookPaper: [
      "📔",
      "📕",
      "📖",
      "📗",
      "📘",
      "📙",
      "📚",
      "📓",
      "📒",
      "📃",
      "📜",
      "📄",
      "📰",
      "🗞️",
      "📑",
      "🔖",
      "🏷️",
    ],
    // Money
    money: ["💰", "💴", "💵", "💶", "💷", "💸", "💳", "🧾", "💹"],
    // Mail
    mail: ["✉️", "📧", "📨", "📩", "📤", "📥", "📦", "📫", "📪", "📬", "📭", "📮", "🗳️"],
    // Writing
    writing: ["✏️", "✒️", "🖋️", "🖊️", "🖌️", "🖍️", "📝"],
    // Office
    office: [
      "💼",
      "📁",
      "📂",
      "🗂️",
      "📅",
      "📆",
      "🗒️",
      "🗓️",
      "📇",
      "📈",
      "📉",
      "📊",
      "📋",
      "📌",
      "📍",
      "📎",
      "🖇️",
      "📏",
      "📐",
      "✂️",
      "🗃️",
      "🗄️",
      "🗑️",
    ],
    // Lock
    lock: ["🔒", "🔓", "🔏", "🔐", "🔑", "🗝️"],
    // Tool
    tool: [
      "🔨",
      "🪓",
      "⛏️",
      "⚒️",
      "🛠️",
      "🗡️",
      "⚔️",
      "🔫",
      "🏹",
      "🛡️",
      "🔧",
      "🔩",
      "⚙️",
      "🗜️",
      "⚖️",
      "🦯",
      "🔗",
      "⛓️",
      "🧰",
      "🧲",
      "⚗️",
      "🧪",
      "🧫",
      "🧬",
      "🔬",
      "🔭",
      "📡",
    ],
    // Science
    science: [
      "💉",
      "🩸",
      "💊",
      "🩹",
      "🩺",
      "🚪",
      "🛏️",
      "🛋️",
      "🪑",
      "🚽",
      "🚿",
      "🛁",
      "🪒",
      "🧴",
      "🧷",
      "🧹",
      "🧺",
      "🧻",
      "🧼",
      "🧽",
      "🧯",
      "🛒",
    ],
  },

  // Symbols - Critical UI elements
  symbols: {
    // Transport-sign
    transportSign: ["🏧", "🚮", "🚰", "♿", "🚹", "🚺", "🚻", "🚼", "🚾", "🛂", "🛃", "🛄", "🛅"],
    // Warning
    warning: ["⚠️", "🚸", "⛔", "🚫", "🚳", "🚭", "🚯", "🚱", "🚷", "📵", "🔞", "☢️", "☣️"],
    // Arrow
    arrow: [
      "⬆️",
      "↗️",
      "➡️",
      "↘️",
      "⬇️",
      "↙️",
      "⬅️",
      "↖️",
      "↕️",
      "↔️",
      "↩️",
      "↪️",
      "⤴️",
      "⤵️",
      "🔃",
      "🔄",
      "🔙",
      "🔚",
      "🔛",
      "🔜",
      "🔝",
    ],
    // Religion
    religion: ["🛐", "⚛️", "🕉️", "✡️", "☸️", "☯️", "✝️", "☦️", "☪️", "☮️", "🕎", "🔯"],
    // Zodiac
    zodiac: ["♈", "♉", "♊", "♋", "♌", "♍", "♎", "♏", "♐", "♑", "♒", "♓", "⛎"],
    // Av-symbol
    avSymbol: [
      "🔀",
      "🔁",
      "🔂",
      "▶️",
      "⏩",
      "⏭️",
      "⏯️",
      "◀️",
      "⏪",
      "⏮️",
      "🔼",
      "⏫",
      "🔽",
      "⏬",
      "⏸️",
      "⏹️",
      "⏺️",
      "⏏️",
      "🎦",
      "🔅",
      "🔆",
      "📶",
      "📳",
      "📴",
    ],
    // Gender
    gender: ["♀️", "♂️", "⚧️"],
    // Math
    math: ["‼️", "⁉️", "❓", "❔", "❕", "❗", "〰️", "💱", "💲"],
    // Punctuation
    punctuation: [
      "⚕️",
      "♾️",
      "🔱",
      "📛",
      "🔰",
      "⭕",
      "✅",
      "☑️",
      "✔️",
      "❌",
      "❎",
      "➰",
      "➿",
      "〽️",
      "✳️",
      "✴️",
      "❇️",
      "©️",
      "®️",
      "™️",
      "#️⃣",
      "*️⃣",
      "0️⃣",
      "1️⃣",
      "2️⃣",
      "3️⃣",
      "4️⃣",
      "5️⃣",
      "6️⃣",
      "7️⃣",
      "8️⃣",
      "9️⃣",
      "🔟",
      "🔠",
      "🔡",
      "🔢",
      "🔣",
      "🔤",
      "🅰️",
      "🆎",
      "🅱️",
      "🆑",
      "🆒",
      "🆓",
      "ℹ️",
      "🆔",
      "Ⓜ️",
      "🆕",
      "🆖",
      "🅾️",
      "🆗",
      "🅿️",
      "🆘",
      "🆙",
      "🆚",
      "🈁",
      "🈂️",
      "🈷️",
      "🈶",
      "🈯",
      "🉐",
      "🈹",
      "🈚",
      "🈲",
      "🉑",
      "🈸",
      "🈴",
      "🈳",
      "㊗️",
      "㊙️",
      "🈺",
      "🈵",
      "🔴",
      "🟠",
      "🟡",
      "🟢",
      "🔵",
      "🟣",
      "🟤",
      "⚫",
      "⚪",
      "🟥",
      "🟧",
      "🟨",
      "🟩",
      "🟦",
      "🟪",
      "🟫",
      "⬛",
      "⬜",
      "◼️",
      "◻️",
      "◾",
      "◽",
      "▪️",
      "▫️",
      "🔶",
      "🔷",
      "🔸",
      "🔹",
      "🔺",
      "🔻",
      "💠",
      "🔘",
      "🔳",
      "🔲",
    ],
  },

  // Flags - Most widely recognized
  flags: {
    // Flag
    flag: ["🏁", "🚩", "🎌", "🏴", "🏳️", "🏳️‍🌈", "🏳️‍⚧️", "🏴‍☠️"],
    // Country-flag (just a subset of most universally recognized)
    countryFlag: [
      "🇺🇸",
      "🇬🇧",
      "🇨🇦",
      "🇯🇵",
      "🇩🇪",
      "🇫🇷",
      "🇮🇹",
      "🇪🇸",
      "🇷🇺",
      "🇨🇳",
      "🇮🇳",
      "🇧🇷",
      "🇦🇺",
      "🇲🇽",
      "🇰🇷",
      "🇸🇦",
      "🇿🇦",
      "🇦🇷",
      "🇪🇬",
      "🇹🇷",
    ],
  },

  // Utility functions for easier access
  getAllEmojis: function () {
    const allEmojis = [];
    const categories = [
      this.smileysEmotion,
      this.peopleBody,
      this.animalsNature,
      this.foodDrink,
      this.travelPlaces,
      this.activities,
      this.objects,
      this.symbols,
      this.flags,
    ];

    categories.forEach((category) => {
      Object.values(category).forEach((subcategory) => {
        if (Array.isArray(subcategory)) {
          allEmojis.push(...subcategory);
        }
      });
    });

    return allEmojis;
  },

  getEmojisByCategory: function (categoryName) {
    return this[categoryName] || {};
  },

  searchEmojis: function (query) {
    // Simple search functionality - could be enhanced
    const allEmojis = this.getAllEmojis();
    return allEmojis.filter((emoji) => {
      // This is a basic implementation - in real use might want more sophisticated search
      return true; // Return all for now, can be enhanced with keywords
    });
  },

  // Get element-specific emojis for the control panel
  getElementEmojis: function (elementType) {
    const elementEmojiMap = {
      Panorama: this.travelPlaces.placeGeographic.concat(["🏠", "🏡", "🏢", "🏛️", "🏰"]),
      Hotspot: this.symbols.arrow.concat(["📍", "🎯", "👆", "👉", "🔍"]),
      Polygon: this.symbols.punctuation.concat(["💎", "🔸", "🔹", "🔺", "🔻"]),
      Video: this.objects.lightVideo.concat(["🎥", "📺", "🎬", "🎞️", "📹"]),
      Webframe: this.objects.computer.concat(["🌐", "💻", "🖥️", "📱", "🖼️"]),
      Image: this.objects.lightVideo.concat(["🖼️", "📷", "📸", "🎨", "🖌️"]),
      Text: this.objects.writing.concat(["📝", "📄", "📃", "✏️", "🖊️"]),
      Business: this.objects.office.concat(["💼", "🏢", "📊", "📈", "💼"]),
      "3DModel": this.objects.tool.concat(["🧊", "📦", "🎲", "⚙️", "🔧"]),
      "3DHotspot": this.activities.game.concat(["🎮", "🕹️", "🎯", "🎲", "🧩"]),
      ProjectedImage: this.objects.lightVideo.concat(["📽️", "🎬", "🎞️", "💡", "🔦"]),
      Element: this.symbols.punctuation.concat(["⚙️", "🔧", "🧰", "⚗️", "🔬"]),
      Container: this.objects.office.concat(["📦", "🗂️", "🗃️", "🗄️", "📁"]),
      "3DModelObject": this.objects.tool.concat(["🧊", "📦", "🎲", "⚙️", "🔧"]),
    };

    return elementEmojiMap[elementType] || this.smileysEmotion.faceSmiling;
  },
};
