/**
 * Comprehensive Font Awesome Icons Library
 * Version 4.5 - Last Update on 11/01/2025 - Search Pro Configuration Loading - Google Sheets / CSV / Business JSON integration, runtime synchronization, Exact matches config, Silence Console Fix
 * Complete icon collection for the Search Pro Control Panel
 */

window.FontAwesomeIcons = {
  // Solid Icons (fas)
  solid: [
    "fas fa-home",
    "fas fa-user",
    "fas fa-cog",
    "fas fa-search",
    "fas fa-envelope",
    "fas fa-phone",
    "fas fa-map-marker-alt",
    "fas fa-heart",
    "fas fa-star",
    "fas fa-edit",
    "fas fa-trash",
    "fas fa-save",
    "fas fa-download",
    "fas fa-upload",
    "fas fa-plus",
    "fas fa-minus",
    "fas fa-times",
    "fas fa-check",
    "fas fa-arrow-left",
    "fas fa-arrow-right",
    "fas fa-arrow-up",
    "fas fa-arrow-down",
    "fas fa-chevron-left",
    "fas fa-chevron-right",
    "fas fa-chevron-up",
    "fas fa-chevron-down",
    "fas fa-angle-left",
    "fas fa-angle-right",
    "fas fa-angle-up",
    "fas fa-angle-down",
    "fas fa-bars",
    "fas fa-list",
    "fas fa-th",
    "fas fa-th-list",
    "fas fa-th-large",
    "fas fa-table",
    "fas fa-calendar",
    "fas fa-clock",
    "fas fa-bell",
    "fas fa-info",
    "fas fa-exclamation",
    "fas fa-question",
    "fas fa-warning",
    "fas fa-ban",
    "fas fa-shield",
    "fas fa-lock",
    "fas fa-unlock",
    "fas fa-key",
    "fas fa-eye",
    "fas fa-eye-slash",
    "fas fa-share",
    "fas fa-link",
    "fas fa-external-link-alt",
    "fas fa-bookmark",
    "fas fa-tag",
    "fas fa-tags",
    "fas fa-folder",
    "fas fa-folder-open",
    "fas fa-file",
    "fas fa-file-alt",
    "fas fa-copy",
    "fas fa-cut",
    "fas fa-paste",
    "fas fa-print",
    "fas fa-fax",
    "fas fa-image",
    "fas fa-images",
    "fas fa-photo",
    "fas fa-picture",
    "fas fa-video",
    "fas fa-film",
    "fas fa-camera",
    "fas fa-music",
    "fas fa-volume-up",
    "fas fa-volume-down",
    "fas fa-volume-off",
    "fas fa-play",
    "fas fa-pause",
    "fas fa-stop",
    "fas fa-forward",
    "fas fa-backward",
    "fas fa-step-forward",
    "fas fa-step-backward",
    "fas fa-eject",
    "fas fa-shopping-cart",
    "fas fa-credit-card",
    "fas fa-money-bill",
    "fas fa-coins",
    "fas fa-gift",
    "fas fa-trophy",
    "fas fa-medal",
    "fas fa-award",
    "fas fa-thumbs-up",
    "fas fa-thumbs-down",
    "fas fa-flag",
    "fas fa-bookmark",
    "fas fa-map",
    "fas fa-globe",
    "fas fa-location-arrow",
    "fas fa-compass",
    "fas fa-directions",
    "fas fa-route",
    "fas fa-car",
    "fas fa-truck",
    "fas fa-bus",
    "fas fa-train",
    "fas fa-plane",
    "fas fa-ship",
    "fas fa-bicycle",
    "fas fa-motorcycle",
    "fas fa-taxi",
    "fas fa-subway",
    "fas fa-walking",
    "fas fa-running",
    "fas fa-building",
    "fas fa-hospital",
    "fas fa-school",
    "fas fa-university",
    "fas fa-church",
    "fas fa-mosque",
    "fas fa-synagogue",
    "fas fa-hotel",
    "fas fa-restaurant",
    "fas fa-coffee",
    "fas fa-utensils",
    "fas fa-wine-glass",
    "fas fa-beer",
    "fas fa-cocktail",
    "fas fa-pizza-slice",
    "fas fa-hamburger",
    "fas fa-ice-cream",
    "fas fa-birthday-cake",
    "fas fa-laptop",
    "fas fa-desktop",
    "fas fa-tablet",
    "fas fa-mobile",
    "fas fa-keyboard",
    "fas fa-mouse",
    "fas fa-headphones",
    "fas fa-microphone",
    "fas fa-camera-retro",
    "fas fa-tv",
    "fas fa-radio",
    "fas fa-gamepad",
    "fas fa-wifi",
    "fas fa-bluetooth",
    "fas fa-usb",
    "fas fa-battery-full",
    "fas fa-battery-half",
    "fas fa-battery-empty",
    "fas fa-plug",
    "fas fa-power-off",
    "fas fa-lightbulb",
    "fas fa-sun",
    "fas fa-moon",
    "fas fa-cloud",
    "fas fa-cloud-rain",
    "fas fa-cloud-snow",
    "fas fa-bolt",
    "fas fa-fire",
    "fas fa-water",
    "fas fa-leaf",
    "fas fa-tree",
    "fas fa-seedling",
    "fas fa-flower",
    "fas fa-bug",
    "fas fa-spider",
    "fas fa-frog",
    "fas fa-fish",
    "fas fa-bird",
    "fas fa-cat",
    "fas fa-dog",
    "fas fa-horse",
    "fas fa-paw",
    "fas fa-bone",
    "fas fa-stethoscope",
    "fas fa-pills",
    "fas fa-syringe",
    "fas fa-thermometer",
    "fas fa-band-aid",
    "fas fa-graduation-cap",
    "fas fa-book",
    "fas fa-bookmark",
    "fas fa-pen",
    "fas fa-pencil-alt",
    "fas fa-eraser",
    "fas fa-ruler",
    "fas fa-calculator",
    "fas fa-microscope",
    "fas fa-flask",
    "fas fa-atom",
    "fas fa-dna",
    "fas fa-tools",
    "fas fa-wrench",
    "fas fa-screwdriver",
    "fas fa-hammer",
    "fas fa-saw",
    "fas fa-drill",
    "fas fa-toolbox",
    "fas fa-hard-hat",
    "fas fa-construction",
    "fas fa-industry",
    "fas fa-factory",
    "fas fa-warehouse",
    "fas fa-paint-brush",
    "fas fa-palette",
    "fas fa-spray-can",
    "fas fa-fill-drip",
    "fas fa-tint",
    "fas fa-brush",
    "fas fa-magic",
    "fas fa-wand-magic",
    "fas fa-sparkles",
    "fas fa-crown",
    "fas fa-gem",
    "fas fa-ring",
    "fas fa-medal",
    "fas fa-ribbon",
    "fas fa-rosette",
    "fas fa-certificate",
    "fas fa-diploma",
    "fas fa-scroll",
    "fas fa-newspaper",
    "fas fa-magazine",
    "fas fa-journal",
    "fas fa-clipboard",
    "fas fa-note-sticky",
    "fas fa-memo",
    "fas fa-quote-left",
    "fas fa-quote-right",
    "fas fa-paragraph",
    "fas fa-text-height",
    "fas fa-text-width",
    "fas fa-font",
    "fas fa-bold",
    "fas fa-italic",
    "fas fa-underline",
    "fas fa-strikethrough",
    "fas fa-superscript",
    "fas fa-subscript",
    "fas fa-align-left",
    "fas fa-align-center",
    "fas fa-align-right",
    "fas fa-align-justify",
    "fas fa-indent",
    "fas fa-outdent",
    "fas fa-list-ul",
    "fas fa-list-ol",
    "fas fa-sort",
    "fas fa-sort-up",
    "fas fa-sort-down",
    "fas fa-filter",
    "fas fa-search-plus",
    "fas fa-search-minus",
    "fas fa-zoom-in",
    "fas fa-zoom-out",
    "fas fa-expand",
    "fas fa-compress",
    "fas fa-resize",
    "fas fa-crop",
    "fas fa-rotate",
    "fas fa-flip-horizontal",
    "fas fa-flip-vertical",
    "fas fa-undo",
    "fas fa-redo",
    "fas fa-history",
    "fas fa-refresh",
    "fas fa-sync",
    "fas fa-spinner",
    "fas fa-circle-notch",
    "fas fa-cog",
    "fas fa-cogs",
    "fas fa-sliders-h",
    "fas fa-toggle-on",
    "fas fa-toggle-off",
    "fas fa-power-off",
    "fas fa-plug",
    "fas fa-battery-full",
    "fas fa-wifi",
    "fas fa-signal",
    "fas fa-rss",
    "fas fa-broadcast-tower",
    "fas fa-satellite",
    "fas fa-radar",
    "fas fa-antenna",
    "fas fa-router",
    "fas fa-modem",
    "fas fa-ethernet",
    "fas fa-server",
    "fas fa-database",
    "fas fa-cloud",
    "fas fa-cloud-upload-alt",
    "fas fa-cloud-download-alt",
    "fas fa-hdd",
    "fas fa-save",
    "fas fa-folder",
    "fas fa-folder-open",
    "fas fa-archive",
    "fas fa-box",
    "fas fa-boxes",
    "fas fa-package",
    "fas fa-shipping-fast",
    "fas fa-truck-loading",
    "fas fa-dolly",
    "fas fa-pallet",
    "fas fa-forklift",
    "fas fa-warehouse",
    "fas fa-store",
    "fas fa-storefront",
    "fas fa-shopping-bag",
    "fas fa-shopping-basket",
    "fas fa-shopping-cart",
    "fas fa-cash-register",
    "fas fa-receipt",
    "fas fa-barcode",
    "fas fa-qrcode",
    "fas fa-price-tag",
    "fas fa-percent",
    "fas fa-chart-line",
    "fas fa-chart-bar",
    "fas fa-chart-pie",
    "fas fa-chart-area",
    "fas fa-analytics",
    "fas fa-trending-up",
    "fas fa-trending-down",
    "fas fa-graph",
    "fas fa-presentation",
    "fas fa-projector",
    "fas fa-slideshow",
    "fas fa-blackboard",
    "fas fa-chalkboard",
    "fas fa-whiteboard",
    "fas fa-easel",
    "fas fa-canvas",
    "fas fa-frame",
    "fas fa-portrait",
    "fas fa-landscape",
    "fas fa-panorama",
    "fas fa-photo-video",
    "fas fa-gallery",
    "fas fa-exhibition",
    "fas fa-museum",
    "fas fa-monument",
    "fas fa-statue",
    "fas fa-landmark",
    "fas fa-castle",
    "fas fa-fortress",
    "fas fa-tower",
    "fas fa-bridge",
    "fas fa-tunnel",
    "fas fa-road",
    "fas fa-highway",
    "fas fa-street",
    "fas fa-sidewalk",
    "fas fa-crosswalk",
    "fas fa-intersection",
    "fas fa-roundabout",
    "fas fa-parking",
    "fas fa-garage",
    "fas fa-gas-station",
    "fas fa-charging-station",
    "fas fa-rest-area",
    "fas fa-picnic-table",
    "fas fa-campground",
    "fas fa-tent",
    "fas fa-rv",
    "fas fa-cabin",
    "fas fa-lodge",
    "fas fa-resort",
    "fas fa-spa",
    "fas fa-gym",
    "fas fa-pool",
    "fas fa-beach",
    "fas fa-mountain",
    "fas fa-volcano",
    "fas fa-desert",
    "fas fa-forest",
    "fas fa-jungle",
    "fas fa-island",
    "fas fa-peninsula",
    "fas fa-continent",
    "fas fa-world",
    "fas fa-earth",
    "fas fa-planet",
    "fas fa-rocket",
    "fas fa-satellite-dish",
    "fas fa-telescope",
    "fas fa-binoculars",
    "fas fa-magnifying-glass",
    "fas fa-loupe",
    "fas fa-window-maximize",
    "fas fa-window-minimize",
    "fas fa-window-restore",
    "fas fa-window-close",
    "fas fa-browser",
    "fas fa-tab",
    "fas fa-bookmark",
    "fas fa-favorites",
    "fas fa-history",
    "fas fa-downloads",
    "fas fa-extensions",
    "fas fa-plugins",
    "fas fa-cube",
    "fas fa-cubes",
    "fas fa-box",
    "fas fa-boxes",
    "fas fa-package",
    "fas fa-container",
    "fas fa-layer-group",
    "fas fa-stack",
    "fas fa-blocks",
    "fas fa-brick",
    "fas fa-wall",
    "fas fa-fence",
    "fas fa-gate",
    "fas fa-door-open",
    "fas fa-door-closed",
    "fas fa-stairs",
    "fas fa-elevator",
    "fas fa-escalator",
    "fas fa-floor",
    "fas fa-ceiling",
    "fas fa-roof",
    "fas fa-foundation",
    "fas fa-blueprint",
    "fas fa-architecture",
    "fas fa-draw-polygon",
    "fas fa-draw-circle",
    "fas fa-draw-square",
    "fas fa-shape",
    "fas fa-geometry",
    "fas fa-triangle",
    "fas fa-diamond",
    "fas fa-hexagon",
    "fas fa-octagon",
    "fas fa-star",
    "fas fa-heart",
    "fas fa-cross",
    "fas fa-circle",
    "fas fa-square",
    "fas fa-rectangle",
    "fas fa-oval",
    "fas fa-ellipse",
    "fas fa-polygon",
    "fas fa-line",
    "fas fa-curve",
    "fas fa-arc",
    "fas fa-spiral",
    "fas fa-wave",
    "fas fa-zigzag",
    "fas fa-grid",
    "fas fa-pattern",
    "fas fa-texture",
    "fas fa-gradient",
    "fas fa-shadow",
    "fas fa-highlight",
    "fas fa-marker",
    "fas fa-pin",
    "fas fa-pushpin",
    "fas fa-thumbtack",
    "fas fa-paperclip",
    "fas fa-staple",
    "fas fa-tape",
    "fas fa-glue",
    "fas fa-scissors",
    "fas fa-ruler-combined",
    "fas fa-compass",
    "fas fa-protractor",
    "fas fa-anchor",
    "fas fa-link",
    "fas fa-chain",
    "fas fa-rope",
    "fas fa-knot",
    "fas fa-thread",
    "fas fa-needle",
    "fas fa-pin",
    "fas fa-safety-pin",
    "fas fa-button",
    "fas fa-zipper",
    "fas fa-velcro",
    "fas fa-magnet",
    "fas fa-attraction",
    "fas fa-repulsion",
    "fas fa-gravity",
    "fas fa-force",
    "fas fa-energy",
    "fas fa-power",
    "fas fa-strength",
    "fas fa-muscle",
    "fas fa-flex",
    "fas fa-stretch",
    "fas fa-compress-alt",
    "fas fa-expand-alt",
    "fas fa-fullscreen",
    "fas fa-minimize",
    "fas fa-maximize",
    "fas fa-restore",
    "fas fa-reset",
    "fas fa-default",
    "fas fa-original",
    "fas fa-backup",
    "fas fa-restore-file",
    "fas fa-version",
    "fas fa-revision",
    "fas fa-branch",
    "fas fa-merge",
    "fas fa-fork",
    "fas fa-split",
    "fas fa-join",
    "fas fa-combine",
    "fas fa-unite",
    "fas fa-separate",
    "fas fa-divide",
    "fas fa-multiply",
    "fas fa-calculate",
    "fas fa-equation",
    "fas fa-formula",
    "fas fa-function",
    "fas fa-variable",
    "fas fa-constant",
    "fas fa-parameter",
    "fas fa-argument",
    "fas fa-value",
    "fas fa-result",
    "fas fa-output",
    "fas fa-input",
    "fas fa-process",
    "fas fa-algorithm",
    "fas fa-logic",
    "fas fa-reasoning",
    "fas fa-thinking",
    "fas fa-brain",
    "fas fa-mind",
    "fas fa-idea",
    "fas fa-lightbulb",
    "fas fa-inspiration",
    "fas fa-creativity",
    "fas fa-innovation",
    "fas fa-invention",
    "fas fa-discovery",
    "fas fa-exploration",
    "fas fa-adventure",
    "fas fa-journey",
    "fas fa-path",
    "fas fa-trail",
    "fas fa-track",
    "fas fa-footprint",
    "fas fa-step",
    "fas fa-walk",
    "fas fa-run",
    "fas fa-sprint",
    "fas fa-marathon",
    "fas fa-race",
    "fas fa-competition",
    "fas fa-tournament",
    "fas fa-championship",
    "fas fa-victory",
    "fas fa-win",
    "fas fa-success",
    "fas fa-achievement",
    "fas fa-accomplishment",
    "fas fa-goal",
    "fas fa-target",
    "fas fa-objective",
    "fas fa-mission",
    "fas fa-purpose",
    "fas fa-intention",
    "fas fa-plan",
    "fas fa-strategy",
    "fas fa-tactic",
    "fas fa-approach",
    "fas fa-method",
    "fas fa-technique",
    "fas fa-skill",
    "fas fa-ability",
    "fas fa-talent",
    "fas fa-gift",
    "fas fa-blessing",
    "fas fa-fortune",
    "fas fa-luck",
    "fas fa-chance",
    "fas fa-opportunity",
    "fas fa-possibility",
    "fas fa-potential",
    "fas fa-capacity",
    "fas fa-capability",
    "fas fa-competence",
    "fas fa-expertise",
    "fas fa-mastery",
    "fas fa-proficiency",
    "fas fa-excellence",
    "fas fa-quality",
    "fas fa-premium",
    "fas fa-superior",
    "fas fa-outstanding",
    "fas fa-exceptional",
    "fas fa-remarkable",
    "fas fa-extraordinary",
    "fas fa-amazing",
    "fas fa-wonderful",
    "fas fa-fantastic",
    "fas fa-incredible",
    "fas fa-unbelievable",
    "fas fa-spectacular",
    "fas fa-magnificent",
    "fas fa-marvelous",
    "fas fa-phenomenal",
    "fas fa-sensational",
    "fas fa-stunning",
    "fas fa-breathtaking",
    "fas fa-awe-inspiring",
    "fas fa-impressive",
  ],

  // Regular Icons (far)
  regular: [
    "far fa-address-book",
    "far fa-address-card",
    "far fa-angry",
    "far fa-arrow-alt-circle-down",
    "far fa-arrow-alt-circle-left",
    "far fa-arrow-alt-circle-right",
    "far fa-arrow-alt-circle-up",
    "far fa-bell",
    "far fa-bell-slash",
    "far fa-bookmark",
    "far fa-building",
    "far fa-calendar",
    "far fa-calendar-alt",
    "far fa-calendar-check",
    "far fa-calendar-minus",
    "far fa-calendar-plus",
    "far fa-calendar-times",
    "far fa-caret-square-down",
    "far fa-caret-square-left",
    "far fa-caret-square-right",
    "far fa-caret-square-up",
    "far fa-chart-bar",
    "far fa-check-circle",
    "far fa-check-square",
    "far fa-circle",
    "far fa-clipboard",
    "far fa-clock",
    "far fa-clone",
    "far fa-closed-captioning",
    "far fa-comment",
    "far fa-comment-alt",
    "far fa-comment-dots",
    "far fa-comments",
    "far fa-compass",
    "far fa-copy",
    "far fa-copyright",
    "far fa-credit-card",
    "far fa-dizzy",
    "far fa-dot-circle",
    "far fa-edit",
    "far fa-envelope",
    "far fa-envelope-open",
    "far fa-eye",
    "far fa-eye-slash",
    "far fa-file",
    "far fa-file-alt",
    "far fa-file-archive",
    "far fa-file-audio",
    "far fa-file-code",
    "far fa-file-excel",
    "far fa-file-image",
    "far fa-file-pdf",
    "far fa-file-powerpoint",
    "far fa-file-video",
    "far fa-file-word",
    "far fa-flag",
    "far fa-flushed",
    "far fa-folder",
    "far fa-folder-open",
    "far fa-frown",
    "far fa-frown-open",
    "far fa-futbol",
    "far fa-gem",
    "far fa-grimace",
    "far fa-grin",
    "far fa-grin-alt",
    "far fa-grin-beam",
    "far fa-grin-beam-sweat",
    "far fa-grin-hearts",
    "far fa-grin-squint",
    "far fa-grin-squint-tears",
    "far fa-grin-stars",
    "far fa-grin-tears",
    "far fa-grin-tongue",
    "far fa-grin-tongue-squint",
    "far fa-grin-tongue-wink",
    "far fa-grin-wink",
    "far fa-hand-lizard",
    "far fa-hand-paper",
    "far fa-hand-peace",
    "far fa-hand-point-down",
    "far fa-hand-point-left",
    "far fa-hand-point-right",
    "far fa-hand-point-up",
    "far fa-hand-pointer",
    "far fa-hand-rock",
    "far fa-hand-scissors",
    "far fa-hand-spock",
    "far fa-handshake",
    "far fa-hdd",
    "far fa-heart",
    "far fa-hospital",
    "far fa-hourglass",
    "far fa-id-badge",
    "far fa-id-card",
    "far fa-image",
    "far fa-images",
    "far fa-keyboard",
    "far fa-kiss",
    "far fa-kiss-beam",
    "far fa-kiss-wink-heart",
    "far fa-laugh",
    "far fa-laugh-beam",
    "far fa-laugh-squint",
    "far fa-laugh-wink",
    "far fa-lemon",
    "far fa-life-ring",
    "far fa-lightbulb",
    "far fa-list-alt",
    "far fa-map",
    "far fa-meh",
    "far fa-meh-blank",
    "far fa-meh-rolling-eyes",
    "far fa-minus-square",
    "far fa-money-bill-alt",
    "far fa-moon",
    "far fa-newspaper",
    "far fa-object-group",
    "far fa-object-ungroup",
    "far fa-paper-plane",
    "far fa-pause-circle",
    "far fa-play-circle",
    "far fa-plus-square",
    "far fa-question-circle",
    "far fa-registered",
    "far fa-sad-cry",
    "far fa-sad-tear",
    "far fa-save",
    "far fa-share-square",
    "far fa-smile",
    "far fa-smile-beam",
    "far fa-smile-wink",
    "far fa-snowflake",
    "far fa-square",
    "far fa-star",
    "far fa-star-half",
    "far fa-sticky-note",
    "far fa-stop-circle",
    "far fa-sun",
    "far fa-surprise",
    "far fa-thumbs-down",
    "far fa-thumbs-up",
    "far fa-times-circle",
    "far fa-tired",
    "far fa-trash-alt",
    "far fa-user",
    "far fa-user-circle",
    "far fa-window-close",
    "far fa-window-maximize",
    "far fa-window-minimize",
    "far fa-window-restore",
  ],

  // Brand Icons (fab)
  brands: [
    "fab fa-500px",
    "fab fa-accessible-icon",
    "fab fa-accusoft",
    "fab fa-acquisitions-incorporated",
    "fab fa-adn",
    "fab fa-adobe",
    "fab fa-adversal",
    "fab fa-affiliatetheme",
    "fab fa-airbnb",
    "fab fa-algolia",
    "fab fa-alipay",
    "fab fa-amazon",
    "fab fa-amazon-pay",
    "fab fa-amilia",
    "fab fa-android",
    "fab fa-angellist",
    "fab fa-angrycreative",
    "fab fa-angular",
    "fab fa-app-store",
    "fab fa-app-store-ios",
    "fab fa-apper",
    "fab fa-apple",
    "fab fa-apple-pay",
    "fab fa-artstation",
    "fab fa-asymmetrik",
    "fab fa-atlassian",
    "fab fa-audible",
    "fab fa-autoprefixer",
    "fab fa-avianex",
    "fab fa-aviato",
    "fab fa-aws",
    "fab fa-bandcamp",
    "fab fa-battle-net",
    "fab fa-behance",
    "fab fa-behance-square",
    "fab fa-bimobject",
    "fab fa-bitbucket",
    "fab fa-bitcoin",
    "fab fa-bity",
    "fab fa-black-tie",
    "fab fa-blackberry",
    "fab fa-blogger",
    "fab fa-blogger-b",
    "fab fa-bluetooth",
    "fab fa-bluetooth-b",
    "fab fa-bootstrap",
    "fab fa-btc",
    "fab fa-buffer",
    "fab fa-buromobelexperte",
    "fab fa-buy-n-large",
    "fab fa-buysellads",
    "fab fa-canadian-maple-leaf",
    "fab fa-cc-amazon-pay",
    "fab fa-cc-amex",
    "fab fa-cc-apple-pay",
    "fab fa-cc-diners-club",
    "fab fa-cc-discover",
    "fab fa-cc-jcb",
    "fab fa-cc-mastercard",
    "fab fa-cc-paypal",
    "fab fa-cc-stripe",
    "fab fa-cc-visa",
    "fab fa-centercode",
    "fab fa-centos",
    "fab fa-chrome",
    "fab fa-chromecast",
    "fab fa-cloudflare",
    "fab fa-cloudscale",
    "fab fa-cloudsmith",
    "fab fa-cloudversify",
    "fab fa-codepen",
    "fab fa-codiepie",
    "fab fa-confluence",
    "fab fa-connectdevelop",
    "fab fa-contao",
    "fab fa-cotton-bureau",
    "fab fa-cpanel",
    "fab fa-creative-commons",
    "fab fa-creative-commons-by",
    "fab fa-creative-commons-nc",
    "fab fa-creative-commons-nc-eu",
    "fab fa-creative-commons-nc-jp",
    "fab fa-creative-commons-nd",
    "fab fa-creative-commons-pd",
    "fab fa-creative-commons-pd-alt",
    "fab fa-creative-commons-remix",
    "fab fa-creative-commons-sa",
    "fab fa-creative-commons-sampling",
    "fab fa-creative-commons-sampling-plus",
    "fab fa-creative-commons-share",
    "fab fa-creative-commons-zero",
    "fab fa-critical-role",
    "fab fa-css3",
    "fab fa-css3-alt",
    "fab fa-cuttlefish",
    "fab fa-d-and-d",
    "fab fa-d-and-d-beyond",
    "fab fa-dailymotion",
    "fab fa-dashcube",
    "fab fa-delicious",
    "fab fa-deploydog",
    "fab fa-deskpro",
    "fab fa-dev",
    "fab fa-deviantart",
    "fab fa-dhl",
    "fab fa-diaspora",
    "fab fa-digg",
    "fab fa-digital-ocean",
    "fab fa-discord",
    "fab fa-discourse",
    "fab fa-dochub",
    "fab fa-docker",
    "fab fa-draft2digital",
    "fab fa-dribbble",
    "fab fa-dribbble-square",
    "fab fa-dropbox",
    "fab fa-drupal",
    "fab fa-dyalog",
    "fab fa-earlybirds",
    "fab fa-ebay",
    "fab fa-edge",
    "fab fa-elementor",
    "fab fa-ello",
    "fab fa-ember",
    "fab fa-empire",
    "fab fa-envira",
    "fab fa-erlang",
    "fab fa-ethereum",
    "fab fa-etsy",
    "fab fa-evernote",
    "fab fa-expeditedssl",
    "fab fa-facebook",
    "fab fa-facebook-f",
    "fab fa-facebook-messenger",
    "fab fa-facebook-square",
    "fab fa-fantasy-flight-games",
    "fab fa-fedex",
    "fab fa-fedora",
    "fab fa-figma",
    "fab fa-firefox",
    "fab fa-firefox-browser",
    "fab fa-first-order",
    "fab fa-first-order-alt",
    "fab fa-firstdraft",
    "fab fa-flickr",
    "fab fa-flipboard",
    "fab fa-fly",
    "fab fa-font-awesome",
    "fab fa-font-awesome-alt",
    "fab fa-font-awesome-flag",
    "fab fa-fonticons",
    "fab fa-fonticons-fi",
    "fab fa-fort-awesome",
    "fab fa-fort-awesome-alt",
    "fab fa-forumbee",
    "fab fa-foursquare",
    "fab fa-free-code-camp",
    "fab fa-freebsd",
    "fab fa-fulcrum",
    "fab fa-galactic-republic",
    "fab fa-galactic-senate",
    "fab fa-get-pocket",
    "fab fa-gg",
    "fab fa-gg-circle",
    "fab fa-git",
    "fab fa-git-alt",
    "fab fa-git-square",
    "fab fa-github",
    "fab fa-github-alt",
    "fab fa-github-square",
    "fab fa-gitkraken",
    "fab fa-gitlab",
    "fab fa-gitter",
    "fab fa-glide",
    "fab fa-glide-g",
    "fab fa-gofore",
    "fab fa-goodreads",
    "fab fa-goodreads-g",
    "fab fa-google",
    "fab fa-google-drive",
    "fab fa-google-play",
    "fab fa-google-plus",
    "fab fa-google-plus-g",
    "fab fa-google-plus-square",
    "fab fa-google-wallet",
    "fab fa-gratipay",
    "fab fa-grav",
    "fab fa-gripfire",
    "fab fa-grunt",
    "fab fa-gulp",
    "fab fa-hacker-news",
    "fab fa-hacker-news-square",
    "fab fa-hackerrank",
    "fab fa-hips",
    "fab fa-hire-a-helper",
    "fab fa-hooli",
    "fab fa-hornbill",
    "fab fa-hotjar",
    "fab fa-houzz",
    "fab fa-html5",
    "fab fa-hubspot",
    "fab fa-imdb",
    "fab fa-instagram",
    "fab fa-instagram-square",
    "fab fa-intercom",
    "fab fa-internet-explorer",
    "fab fa-invision",
    "fab fa-ioxhost",
    "fab fa-itch-io",
    "fab fa-itunes",
    "fab fa-itunes-note",
    "fab fa-java",
    "fab fa-jedi-order",
    "fab fa-jenkins",
    "fab fa-jira",
    "fab fa-joget",
    "fab fa-joomla",
    "fab fa-js",
    "fab fa-js-square",
    "fab fa-jsfiddle",
    "fab fa-kaggle",
    "fab fa-keybase",
    "fab fa-keycdn",
    "fab fa-kickstarter",
    "fab fa-kickstarter-k",
    "fab fa-korvue",
    "fab fa-laravel",
    "fab fa-lastfm",
    "fab fa-lastfm-square",
    "fab fa-leanpub",
    "fab fa-less",
    "fab fa-line",
    "fab fa-linkedin",
    "fab fa-linkedin-in",
    "fab fa-linode",
    "fab fa-linux",
    "fab fa-lyft",
    "fab fa-magento",
    "fab fa-mailchimp",
    "fab fa-mandalorian",
    "fab fa-markdown",
    "fab fa-mastodon",
    "fab fa-maxcdn",
    "fab fa-mdb",
    "fab fa-medapps",
    "fab fa-medium",
    "fab fa-medium-m",
    "fab fa-medrt",
    "fab fa-meetup",
    "fab fa-megaport",
    "fab fa-mendeley",
    "fab fa-microsoft",
    "fab fa-mix",
    "fab fa-mixcloud",
    "fab fa-mizuni",
    "fab fa-modx",
    "fab fa-monero",
    "fab fa-napster",
    "fab fa-neos",
    "fab fa-nimblr",
    "fab fa-node",
    "fab fa-node-js",
    "fab fa-npm",
    "fab fa-ns8",
    "fab fa-nutritionix",
    "fab fa-odnoklassniki",
    "fab fa-odnoklassniki-square",
    "fab fa-old-republic",
    "fab fa-opencart",
    "fab fa-openid",
    "fab fa-opera",
    "fab fa-optin-monster",
    "fab fa-orcid",
    "fab fa-osi",
    "fab fa-page4",
    "fab fa-pagelines",
    "fab fa-palfed",
    "fab fa-patreon",
    "fab fa-paypal",
    "fab fa-penny-arcade",
    "fab fa-periscope",
    "fab fa-phabricator",
    "fab fa-phoenix-framework",
    "fab fa-phoenix-squadron",
    "fab fa-php",
    "fab fa-pied-piper",
    "fab fa-pied-piper-alt",
    "fab fa-pied-piper-hat",
    "fab fa-pied-piper-pp",
    "fab fa-pied-piper-square",
    "fab fa-pinterest",
    "fab fa-pinterest-p",
    "fab fa-pinterest-square",
    "fab fa-playstation",
    "fab fa-product-hunt",
    "fab fa-pushed",
    "fab fa-python",
    "fab fa-qq",
    "fab fa-quinscape",
    "fab fa-quora",
    "fab fa-r-project",
    "fab fa-raspberry-pi",
    "fab fa-ravelry",
    "fab fa-react",
    "fab fa-reacteurope",
    "fab fa-readme",
    "fab fa-rebel",
    "fab fa-red-river",
    "fab fa-reddit",
    "fab fa-reddit-alien",
    "fab fa-reddit-square",
    "fab fa-redhat",
    "fab fa-renren",
    "fab fa-replyd",
    "fab fa-researchgate",
    "fab fa-resolving",
    "fab fa-rev",
    "fab fa-rocketchat",
    "fab fa-rockrms",
    "fab fa-safari",
    "fab fa-salesforce",
    "fab fa-sass",
    "fab fa-schlix",
    "fab fa-scribd",
    "fab fa-searchengin",
    "fab fa-sellcast",
    "fab fa-sellsy",
    "fab fa-servicestack",
    "fab fa-shirtsinbulk",
    "fab fa-shopware",
    "fab fa-simplybuilt",
    "fab fa-sistrix",
    "fab fa-sith",
    "fab fa-sketch",
    "fab fa-skyatlas",
    "fab fa-skype",
    "fab fa-slack",
    "fab fa-slack-hash",
    "fab fa-slideshare",
    "fab fa-snapchat",
    "fab fa-snapchat-ghost",
    "fab fa-snapchat-square",
    "fab fa-soundcloud",
    "fab fa-sourcetree",
    "fab fa-speakap",
    "fab fa-speaker-deck",
    "fab fa-spotify",
    "fab fa-squarespace",
    "fab fa-stack-exchange",
    "fab fa-stack-overflow",
    "fab fa-stackpath",
    "fab fa-staylinked",
    "fab fa-steam",
    "fab fa-steam-square",
    "fab fa-steam-symbol",
    "fab fa-sticker-mule",
    "fab fa-strava",
    "fab fa-stripe",
    "fab fa-stripe-s",
    "fab fa-studiovinari",
    "fab fa-stumbleupon",
    "fab fa-stumbleupon-circle",
    "fab fa-superpowers",
    "fab fa-supple",
    "fab fa-suse",
    "fab fa-swift",
    "fab fa-symfony",
    "fab fa-teamspeak",
    "fab fa-telegram",
    "fab fa-telegram-plane",
    "fab fa-tencent-weibo",
    "fab fa-the-red-yeti",
    "fab fa-themeco",
    "fab fa-themeisle",
    "fab fa-think-peaks",
    "fab fa-trade-federation",
    "fab fa-trello",
    "fab fa-tripadvisor",
    "fab fa-tumblr",
    "fab fa-tumblr-square",
    "fab fa-twitch",
    "fab fa-twitter",
    "fab fa-twitter-square",
    "fab fa-typo3",
    "fab fa-uber",
    "fab fa-ubuntu",
    "fab fa-uikit",
    "fab fa-umbraco",
    "fab fa-uncharted",
    "fab fa-uniregistry",
    "fab fa-unity",
    "fab fa-untappd",
    "fab fa-ups",
    "fab fa-usb",
    "fab fa-usps",
    "fab fa-ussunnah",
    "fab fa-vaadin",
    "fab fa-viacoin",
    "fab fa-viadeo",
    "fab fa-viadeo-square",
    "fab fa-viber",
    "fab fa-vimeo",
    "fab fa-vimeo-square",
    "fab fa-vimeo-v",
    "fab fa-vine",
    "fab fa-vk",
    "fab fa-vnv",
    "fab fa-vuejs",
    "fab fa-waze",
    "fab fa-weebly",
    "fab fa-weibo",
    "fab fa-weixin",
    "fab fa-whatsapp",
    "fab fa-whatsapp-square",
    "fab fa-whmcs",
    "fab fa-wikipedia-w",
    "fab fa-windows",
    "fab fa-wix",
    "fab fa-wizards-of-the-coast",
    "fab fa-wolf-pack-battalion",
    "fab fa-wordpress",
    "fab fa-wordpress-simple",
    "fab fa-wpbeginner",
    "fab fa-wpexplorer",
    "fab fa-wpforms",
    "fab fa-wpressr",
    "fab fa-xbox",
    "fab fa-xing",
    "fab fa-xing-square",
    "fab fa-y-combinator",
    "fab fa-yahoo",
    "fab fa-yammer",
    "fab fa-yandex",
    "fab fa-yandex-international",
    "fab fa-yarn",
    "fab fa-yelp",
    "fab fa-yoast",
    "fab fa-youtube",
    "fab fa-youtube-square",
    "fab fa-zhihu",
  ],
};

// Comprehensive emoji collection organized by categories
window.EmojiLibrary = {
  // General/Common emojis
  general: [
    "🏠",
    "📍",
    "💎",
    "🎥",
    "🌐",
    "🖼️",
    "📝",
    "🏢",
    "🎯",
    "📌",
    "⭐",
    "✨",
    "🔸",
    "🔹",
    "🟣",
    "🟢",
    "🟡",
    "🔴",
    "🟠",
    "🟤",
    "⚫",
    "⚪",
    "🔵",
    "🟨",
    "🟧",
    "🟪",
    "🟫",
    "⬛",
    "⬜",
    "🔶",
    "🔷",
    "🔸",
    "🔹",
    "💠",
    "🔘",
    "🔳",
    "🔲",
    "✅",
    "❌",
    "❎",
    "✔️",
    "❕",
    "❗",
    "❓",
    "❔",
    "💯",
    "🔟",
    "🔢",
    "🔤",
    "🔠",
    "🔡",
    "🆔",
    "🆕",
    "🆓",
    "🆙",
    "🆗",
    "🆒",
    "🆖",
    "🈁",
    "🈯",
    "🈳",
    "🈵",
    "🈶",
    "🈚",
    "🈲",
    "🉐",
    "🈴",
    "🈺",
    "🈸",
    "🈷️",
  ],

  // Home/Building related
  home: [
    "🏠",
    "🏡",
    "🏘️",
    "🏚️",
    "🏗️",
    "🏭",
    "🏢",
    "🏬",
    "🏣",
    "🏤",
    "🏥",
    "🏦",
    "🏨",
    "🏪",
    "🏫",
    "🏩",
    "💒",
    "🏛️",
    "⛪",
    "🕌",
    "🕍",
    "🛕",
    "🏟️",
    "🏞️",
    "🗻",
    "🏔️",
    "⛰️",
    "🌋",
    "🗾",
    "🏕️",
    "🏖️",
    "🏜️",
    "🏝️",
    "🏞️",
    "🎪",
    "🎠",
    "🎡",
    "🎢",
    "🚂",
    "🚃",
  ],

  // Navigation/Location
  navigation: [
    "📍",
    "📌",
    "🗺️",
    "🧭",
    "🎯",
    "📍",
    "📌",
    "🚩",
    "🏁",
    "🏳️",
    "🏴",
    "🎌",
    "🏳️‍🌈",
    "🏳️‍⚧️",
    "🏴‍☠️",
    "🗺️",
    "🧭",
    "⛰️",
    "🏔️",
    "🗻",
    "🌋",
    "🏕️",
    "🏖️",
    "🏜️",
    "🏝️",
    "🏞️",
    "🗾",
    "🌍",
    "🌎",
    "🌏",
    "🌐",
    "🗺️",
    "🧭",
    "📍",
    "📌",
    "🎯",
    "🚩",
    "🏁",
    "🏳️",
    "🏴",
  ],

  // Media/Video
  media: [
    "🎥",
    "📹",
    "🎬",
    "🎞️",
    "📽️",
    "🎦",
    "📺",
    "📻",
    "🎵",
    "🎶",
    "🎼",
    "🎹",
    "🥁",
    "🎷",
    "🎺",
    "🎸",
    "🪕",
    "🎻",
    "🎤",
    "🎧",
    "📱",
    "💻",
    "🖥️",
    "🖨️",
    "⌨️",
    "🖱️",
    "🖲️",
    "💽",
    "💾",
    "💿",
    "📀",
    "🎮",
    "🕹️",
    "📷",
    "📸",
    "📼",
    "🔍",
    "🔎",
    "💡",
    "🔦",
  ],

  // Web/Technology
  web: [
    "🌐",
    "💻",
    "📱",
    "🖥️",
    "⌨️",
    "🖱️",
    "🖲️",
    "💾",
    "💿",
    "📀",
    "💽",
    "🗄️",
    "🖨️",
    "📠",
    "📞",
    "☎️",
    "📟",
    "📺",
    "📻",
    "🎮",
    "🕹️",
    "📷",
    "📸",
    "📹",
    "🎥",
    "🎬",
    "🎞️",
    "📽️",
    "🎦",
    "📺",
    "🔌",
    "🔋",
    "🪫",
    "💡",
    "🔦",
    "🕯️",
    "🧯",
    "🛢️",
    "💸",
    "💵",
  ],

  // Images/Pictures
  images: [
    "🖼️",
    "🎨",
    "🖌️",
    "🖍️",
    "📸",
    "📷",
    "🎞️",
    "📽️",
    "🎬",
    "🎥",
    "🖥️",
    "📺",
    "💻",
    "📱",
    "🖱️",
    "⌨️",
    "🖲️",
    "💾",
    "💿",
    "📀",
    "💽",
    "🗄️",
    "🖨️",
    "📠",
    "🔍",
    "🔎",
    "💡",
    "🔦",
    "🕯️",
    "🧯",
    "🌅",
    "🌄",
    "🌇",
    "🌆",
    "🏙️",
    "🌃",
    "🌌",
    "🌉",
    "🌁",
    "🌠",
  ],

  // Text/Documents
  text: [
    "📝",
    "📄",
    "📃",
    "📑",
    "📊",
    "📈",
    "📉",
    "🗒️",
    "🗓️",
    "📅",
    "📆",
    "🗑️",
    "📇",
    "🗃️",
    "🗳️",
    "🗄️",
    "📋",
    "📌",
    "📍",
    "📎",
    "🖇️",
    "📏",
    "📐",
    "✂️",
    "🖊️",
    "🖋️",
    "✒️",
    "🖌️",
    "🖍️",
    "📝",
    "✏️",
    "📖",
    "📚",
    "📙",
    "📘",
    "📗",
    "📕",
    "📒",
    "📓",
    "📔",
  ],

  // Business/Buildings
  business: [
    "🏢",
    "🏬",
    "🏪",
    "🏭",
    "🏗️",
    "🏘️",
    "🏚️",
    "🏠",
    "🏡",
    "🏛️",
    "🏣",
    "🏤",
    "🏥",
    "🏦",
    "🏨",
    "🏩",
    "💒",
    "⛪",
    "🕌",
    "🕍",
    "🛕",
    "🏟️",
    "🎪",
    "🎠",
    "🎡",
    "🎢",
    "🎭",
    "🎨",
    "🎯",
    "🎳",
    "💼",
    "👔",
    "👗",
    "👘",
    "👙",
    "👚",
    "👛",
    "👜",
    "👝",
    "🎒",
  ],

  // 3D/Geometric
  geometric: [
    "📦",
    "📫",
    "📪",
    "📬",
    "📭",
    "📮",
    "🗳️",
    "✉️",
    "📧",
    "📨",
    "📩",
    "📤",
    "📥",
    "📦",
    "📫",
    "📪",
    "📬",
    "📭",
    "📮",
    "🗳️",
    "🔲",
    "🔳",
    "⬛",
    "⬜",
    "◼️",
    "◻️",
    "◾",
    "◽",
    "▪️",
    "▫️",
    "🔶",
    "🔷",
    "🔸",
    "🔹",
    "🔺",
    "🔻",
    "💠",
    "🔘",
    "🔲",
    "🔳",
  ],

  // Containers/Boxes
  containers: [
    "📦",
    "📫",
    "📪",
    "📬",
    "📭",
    "📮",
    "🗳️",
    "🗄️",
    "🗃️",
    "📋",
    "🗒️",
    "🗓️",
    "📅",
    "📆",
    "🗑️",
    "📇",
    "🗂️",
    "📂",
    "📁",
    "🗄️",
    "🗃️",
    "🗳️",
    "🔒",
    "🔓",
    "🔐",
    "🔑",
    "🗝️",
    "🔨",
    "⛏️",
    "⚒️",
  ],
};
